name: gnome-clocks
adopt-info: gnome-clocks
summary: Simple GNOME app with stopwatch, timer, and world clock support
description: |
  GNOME Clocks is a simple application to show the time and date in multiple
  locations and set alarms or timers. A stopwatch is also included.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core22

layout:
  /usr/share/libgweather-4:
    symlink: $SNAP/usr/share/libgweather-4
  /usr/lib/$CRAFT_ARCH_TRIPLET/libgweather-4:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/libgweather-4

# Launchpad doesn't recognize these fields yet
passthrough:
  license: GPL-2.0+
  title: GNOME Clocks

slots:
  # for GtkApplication registration
  gnome-clocks:
    interface: dbus
    bus: session
    name: org.gnome.clocks

apps:
  gnome-clocks:
    command: usr/bin/gnome-clocks
    extensions: [ gnome ]
    plugs:
      - audio-playback
    desktop: usr/share/applications/org.gnome.clocks.desktop

parts:
  snapbuildtools:
    source: https://github.com/sergio-costas/snap-build-tools.git
    source-depth: 1
    plugin: nil
    override-pull: |
      craftctl default
      $CRAFT_PART_SRC/install

  gnome-clocks:
    after: [snapbuildtools]
    source: https://gitlab.gnome.org/GNOME/gnome-clocks.git
    source-tag: '45.0'
# ext:updatesnap
#   version-format:
#     lower-than: '46'
#     no-9x-revisions: true
    source-depth: 1
    source-type: git
    plugin: meson
    parse-info: [usr/share/metainfo/org.gnome.clocks.appdata.xml]
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    build-packages:
      - itstool
      - gettext
      - gsettings-desktop-schemas-dev
      - desktop-file-utils
      - appstream-util
      - appstream
      - libgnome-desktop-3-dev
      - libgeoclue-2-dev
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10)
    build-environment:
      - PATH: $CRAFT_STAGE/usr/bin:$PATH
      - ACLOCAL_PATH: $CRAFT_STAGE/usr/share/aclocal
      - XDG_DATA_DIRS: $CRAFT_STAGE/usr/share:/usr/share:$XDG_DATA_DIRS
      - LD_LIBRARY_PATH: $CRAFT_STAGE/usr/lib/vala-0.54:$CRAFT_STAGE/usr/lib:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH
      - GDK_PIXBUF_MODULE_FILE: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/2.10.0/loaders.cache
      - PKG_CONFIG_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:$CRAFT_STAGE/usr/lib/pkgconfig:$CRAFT_STAGE/usr/share/pkgconfig:$PKG_CONFIG_PATH
    stage-packages:
      - libgeoclue-2-0
    build-snaps: [core22, gtk-common-themes, gnome-42-2204]
    override-build: |
      $CRAFT_PROJECT_DIR/snapbuildtools/remove_common.py core22 gtk-common-themes gnome-42-2204
      craftctl default
      sed -i 's|Icon=org.gnome.clocks$|Icon=${SNAP}/meta/gui/org.gnome.clocks.svg|g' $CRAFT_PART_INSTALL/usr/share/applications/org.gnome.clocks.desktop
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp $CRAFT_PART_SRC/data/icons/hicolor/scalable/apps/org.gnome.clocks.svg $CRAFT_PART_INSTALL/meta/gui/

  cleanup:
    after: [ gnome-clocks ]
    plugin: nil
    override-prime: |
      set -eux
      rm -rf usr/share/doc
      rm -rf usr/share/man
      rm -rf usr/libexec/*/installed-tests
      rm -rf usr/libexec/installed-tests
      rm -f usr/lib/*.la
      rm -f usr/lib/*/*.la
      rm -rf usr/include
      rm -rf usr/lib/$CRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0
      rm -rf usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig
      find . -type d -empty -delete
      glib-compile-schemas $CRAFT_PRIME/usr/share/glib-2.0/schemas